### PR TITLE
Add multiple filetypes as javscript,html and css

### PR DESCRIPTION
**Pull request by breneser**
I actually don't know much about Vim script or plugins, not sure if there are any other caveats I need to consider, but I thought solution would easily be adding multiple file types. It seems to be working well for me.

### CODE REVIEW

**Comment by posva** [comment]
Can you tell me about something you cannot do without setting the ft to multiple?

**Comment by breneser** [comment]
I use [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) for autocomplete functionality. Which uses filetypes to populate autocomplete list. I can not see javascript autocomplete unless I set filetype to javascript. Which I can do by modifying my vimrc file, but thought it should be in the plugin for better integration.

**Comment by adriaanzon** [comment]
This broke some `FileType vue` autocommands for me. Do I have to edit them to `FileType vue.html.javascript.css` or is there a better way to deal with this?

**Comment by posva** [comment]
@adriaanzon That's curious. I actually don't know if there's a better way of dealing with it. I don't know much about the compound filetypes. Maybe you can check if it's starts with `vue`

**Comment by adriaanzon** [comment]
`autocmd FileType vue*` seems to work fine, thanks for the suggestion :smiley:

**Pull request merged**
