### PR TITLE
Supporting i18n tag

### PR DESCRIPTION
**Pull request by ycmjason**
Although i18n is not an official package, it is quite a popular package in the Vue ecosystem. It might be worth to add support for `<i18n>`.

https://kazupon.github.io/vue-i18n/guide/sfc.html

### CODE REVIEW

**Comment by posva** [comment]
This could be nice indeed!

**Comment by adriaanzon** [comment]
I would like to hold off on adding new languages until there is a solution to the slowness problem mentioned in #97. Until then, this will add up to the languages being loaded, which will make editing Vue files slower.

**Comment by posva** [comment]
I see, I didn't know it would affect the slowness, I'm glad you thought about it 🙂

**Comment by babelfish** [comment]
I was just doing this... should have checked to see if there was a PR for it. Would've saved me a lot of irritation dealing with Vim script. Assuming this ever gets merged, I would suggest using YAML for the i18n block syntax highlighting. Since YAML is a superset of JSON it will be able to highlight the i18n block whether you're using the default of JSON or have it configured to use YAML.

**Pull request closed without merging**
