### PR TITLE
add ' ' support for pug, jade, stylus, scss, sass & less

### PR DESCRIPTION
**Pull request by larry-wong**

### CODE REVIEW

**Comment by posva** [comment]
Why should we support `<style lang='sass'>` too?

**Comment by larry-wong** [comment]
@posva Thank you for your response. Vue supports it (My vue version is 2.10). And I'm used to typing ' instead of " in html/js files. So I think there should be somebody else like me. :)

**Comment by zhiyand** [comment]
@posva Indeed, Vue supports different preprocessors for styles and templates, and <style lang='stylus'> breaks the syntax highlighting in the current `vim-vue` implementation.

Maybe a more flexible approach would be to allow attributes of the top level tags in Vue files. That way, if future Vue versions adds support for other attributes other than `lang` and `scoped`, this plugin still stays compatible.

**Comment by posva** [comment]
@zhiyand Absolutely and there's even more: custom blocks (eg: `<example name="foo">`) I think we should support them all (using HTML parser by default).

Let's merge this and test that later

**Pull request merged**
