### PR TITLE
Add eslint checker for Vue to Syntastic

### PR DESCRIPTION
**Pull request by knight42**

### CODE REVIEW

**Comment by posva** [comment]
Thank you! Testing this asap before merging!

**Comment by knight42** [comment]
@posva Are there any problems?

**Comment by posva** [comment]
@knight42 Thanks for for bumping! I absolutely forgot 😓
Testing right now

**Comment by posva** [comment]
Works nicely! Thank you very much for this 😄

**Comment by adriaanzon** [comment]
Hi @knight42, I replaced the Syntastic file by one that uses Syntastic's 'redirect' option to redirect to `javascript/eslint` here: https://github.com/posva/vim-vue/commit/f72aac329acad4ed8401df1df2f2fc1a2a7e1a9f#diff-bf5df5a43e01e4596d5659cdb3dd80e5.

You think this is fine or were there any things that your file did different than [javascript/eslint](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/javascript/eslint.vim)?

**Pull request merged**
