### PR TITLE
Indentation for html, js, stylus, and pug

### LINKED ISSUE #7: Indentation rules?
I gave vue components a shot for the first time yesterday, and while the syntax highlighting for different regions seems to be working fine, I don't get any indentation rules. In my set up at least, I get no auto-indentation whatsoever, which is pretty annoying. (I'm using filetype indent settings with `filetype plugin indent on`.)

Is there any possibility of getting vim to adjust indentation settings to match the syntax regions this sets up?

### PR DESCRIPTION
**Pull request by bopjesvla**
fixes #7

### CODE REVIEW

**Comment by posva** [comment]
That's a huge PR, thank you very much for it. I'm checking it tonight 😄

**Comment by bopjesvla** [comment]
Don't be intimidated, the first commit is html5.vim's indentation which can be assumed to be working.

**Comment by posva** [comment]
@bopjesvla It doesn't seem to indent html, jade or stylus when I try it. Do you need any specific extra plugin for this to work?

**Comment by bopjesvla** [comment]
My guess is that this wasn't installed properly, or that you have a conflicting plugin. Can you verify that indent/vue.vim exists? If that's the case, can you install html5.vim and check if indentation works for you in HTML files?

**Comment by mixedCase** [comment]
Works great for me, tested with a clean and my everyday busy config. Indented HTML and JS and did not indent CSS. Hope to see that one added :smile:

**Comment by mixedCase** [comment]
I forgot to say, I did experience this: https://i.imgur.com/Byq7QK0.png

First line just says there was an error parsing that file.

As for the other two red lines, "No existe la variable" means "variable doesn't exist".

Nevertheless, it does seem to work as I mentioned.

**Comment by adriaanzon** [comment]
Why not simply use `runtime! indent/html.vim` for html indentation?

**Comment by mixedCase** [comment]
@adriaanzon ...I can't believe it was this simple all along. That works.

**Comment by posva** [comment]
@adriaanzon Where should this be added?

**Comment by adriaanzon** [comment]
@posva in `indent/vue.vim`. 

You could use `$VIMRUNTIME/indent/scss.vim` as an example:

```vim
if exists("b:did_indent")
  finish
endif

runtime! indent/css.vim
```

**Comment by posva** [comment]
@adriaanzon Do you have a working example of this?
My `indent/vue.vim` is as follows but I indenting does nothing. Although new lines are created with the appropriate indentation level.

```viml
if exists("b:did_indent")
  finish
endif

runtime! indent/stylus.vim
let s:stylindent = &indentexpr

unlet b:did_indent
runtime! indent/pug.vim
let s:pugindent = &indentexpr

unlet b:did_indent
runtime! indent/javascript.vim
let s:jsindent = &indentexpr

unlet b:did_indent
runtime! indent/css.vim
let s:cssindent = &indentexpr

unlet b:did_indent
runtime! indent/html.vim
let s:htmlindent = &indentexpr

let b:did_indent = 1
```

It'd be great if you could create a pull request if your `indent/vue.vim` works better 😄

**Comment by adriaanzon** [comment]
I only tried indenting html/css/js with `runtime! indent/html.vim` and that worked fine for me. Do you have an example of where js indenting failed for you?

You don't need to use `runtime!` for javascript and css because `indent/html.vim` already handles those for you.

For pug/stylus/others you would need to detect the regions where it's contained and then apply the indentexpr for that language. I'm quite familiar with indenting multiple languages in one file (did it for vim-blade) so I will have a look at this.

**Comment by posva** [comment]
Closing this in favour of #23 
Sorry @bopjesvla 😓

**Pull request closed without merging**
