### PR TITLE
Add support for typescript and improve html support

### PR DESCRIPTION
**Pull request by esdras**

### CODE REVIEW

**Comment by esdras** [comment]
Sorry, I got ahead of myself and didn't notice that lang="typescript" messes with the webpack loader. 

I'm using like this: <script ts></script>, it works, but not sure if this is a good approach.
Anyways, here is the commit, let me know if you want a PR.

https://github.com/esdras/vim-vue/commit/51b18f8b907aaaad524368404a057c570b64dee0

Cheers.

**Comment by posva** [comment]
Do you have an example of a Vue component written in Typescript? Isn't there any attribute needed to the script tag? If not, I think using a ts tag is enough, it should also be added to the readme

**Comment by esdras** [comment]
Typescript must be transpiled to javascript in order to run in the browser, we only use typescript features in development, so there is no need for an attribute to the script tag. In my case the ts attribute is discarded by webpack.

```vue
<template>
...
</template>

<script ts>
import * as Vue from 'vue'
import { mapMutations, mapGetters } from 'vuex'
import { Conversation, Operator, Message } from '../store/state'

interface Modal extends Vue {
  currentConversation: Conversation,
  operator: Operator,
  message: Message
}

export default {
  name: 'modal',
  computed: {
    ...mapGetters(['currentConversation']),
    message: function(){
      return this.currentConversation.messages[0]
    },
    operator: function() {
      return this.currentConversation.operator
    }
  },
  methods: {
    ...mapMutations(['toggleModal'])
  }
} as Vue.ComponentOptions<Modal>
</script>

<style>
...
</style>

```

**Comment by posva** [comment]
Yeah, vue-loader will ignore it.
can you please add a PR with your commit and also add a note on the Readme about it?

**Comment by arian-granular** [comment]
Can you add the original regex back so both `ts` and  `lang="ts"` will match? The `lang="ts"` attribute is necessary for tsify.

For what it's worth, [this official example uses that attribute and webpack without issue. ](https://github.com/vuejs/vue-class-component/blob/master/example/App.vue#L12)

**Pull request closed without merging**
